name: cougar
main: com.github.sqyyy.cougar.plugin.CougarDatasetPlugin
version: 0.1.0-alpha
api-version: 1.19
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.22
commands:
  cougar:
    usage: /cougar